### ISSUE TITLE
Clearer message for plugin state test failure

### ISSUE THREAD

**Issue by SamWindell** [free-audio/clap-validator#10]
It took me a while to realise what was going on when I was getting the message:
```
     FAILED: Re-saving the loaded state resulted in a different state file.
       Expected: '/run/user/1000/clap-validator/com.FrozenPlain.Mirage/state-
       reproducibility-basic/state-expected'. Actual: '/run/user/1000/clap-
       validator/com.FrozenPlain.Mirage/state-reproducibility-basic/state-
       actual'.
```

What I now understand it means is that while the parameters are correct after calling clap_plugin_param::get_value(), the state is not the same: clap_plugin_state::save() differs directly after calling clap_plugin_state::load(). The filepaths that the error shows are there so that you can diff the files to work out what's going wrong.

A possible alternate error message would be:
```
The state of the plugin is not reversible: using the clap state extension, 
doing a save() -> load() -> save() does not equal the same state. This file 
shows what we expect the state to be: {}, and this file is the actual state: {}.
```

**Comment by robbert-vdh** [comment]
Right above that it says:

```
   - state-reproducibility-basic: Randomizes a plugin's parameters, saves its state, recreates the plugin instance, reloads the state, and then checks
       whether the parameter values are the same and whether saving the state once more results in the same state file as before. The parameter values are
       updated using the process function.
```

Isn't it clear what 're-saving the loaded state' means based on that?

**Comment by SamWindell** [comment]
I did have 10 minutes of head scratching despite both the messages. I think a long informative message would have helped the issue, but maybe that's not for everyone. So entirely up to you if you want to make a change.
