### ISSUE TITLE
Validator passes invalid plugin_path to clap_plugin_entry::init when trying to load bundle on MacOS

### ISSUE THREAD

**Issue by roelofvkr** [free-audio/clap-validator#12]
According to [this comment](https://github.com/free-audio/clap/discussions/102#discussioncomment-2977575) the plugin_path argument on the clap_plugin_entry::init should point to the DLL on windows or the Bundle on MacOS. However, right now the validator passes the actual library within the bundle when initialising. 

The issue to me seems to be [here](https://github.com/free-audio/clap-validator/blob/a9a7b644f9f4bf96918b1e0a7935fe2507bfb4cc/src/plugin/library.rs#L116), where the path for loading the library is updated to deal with the fact that it's a bundle. This path is then also passed to the init function, when the original path should be.

**Comment by robbert-vdh** [comment]
The correct behavior is now specified as of https://github.com/free-audio/clap/commit/f6d86a7e7c9cd3da233cb9ffa8e54396000ecabf. So this is the DSO on any platform except for macOS, where the path points to the bundle.
