### ISSUE TITLE
param-conversions test inconsistent

### ISSUE THREAD

**Issue by sadko4u** [free-audio/clap-validator#14]
The test can be inconsistent because of additional conversions related to floating-point rounding.

Consider this:
```
param-conversions: Asserts that value to string and string to value conversions are supported for ether all or none of the plugin's parameters, and that conversions between values and strings roundtrip consistently.
     FAILED: Converting 0.8329472322266984 to a string, back to a value, and then back to a string again for parameter 1665076118 ('Filter Width 7') results in '10.00 oct' -> 0.8333333134651184 -> '10.0 oct', which is not consistent.
```

The parameter `Filter Width 7` is a linear value which is normalized to range `[0..1]` in LSP plugin framework.
1. The actual minimum value is `0` and the maximum one is `12`.
2. So the simple conversion `0 + 0.8329472322266984 * 12` gives `9.99536678672` which is less than 10 but is rounded to `10.00 oct` when formatting. Because the actual value is less than `10`, the number formatting engine decides to use two digits after the floating-point value and we get `10.00 oct`.
3. When parsing `10.00 oct` we get value of `10 / 12 = 0.833333333333`.
4. When formatting back `0.833333333333` we get the exact value `10`, and the number formatting engine decides to use one digit after the floating-point value, so we get `10.0 oct`.

**Comment by robbert-vdh** [comment]
You can change your formatting logic to use a fixed number of decimals in this case.

**Comment by sadko4u** [comment]
This won't solve the problem because the value we're displaying the user never will be of the same precision as it is stored in the memory. We don't need to show to the user all 6 digits after decimal point because they don't make any sence, just polluting the UI with unnecessary information. And there always will be rounding errors after calling the `logf()` and `expf()` functions which may yield to such result.

**Comment by robbert-vdh** [comment]
So what I'm saying is to always show two decimals, rather than one or two depending on the value. That makes the output consistent.

**Comment by sadko4u** [comment]
It is not good for values that are displayed linear but are designated to change in logarithmic progression.

**Comment by robbert-vdh** [comment]
So you want to increase the display precision with the value? You can indeed do that. Anyways, this is not an issue with the validator test so I'm closing this issue.

**Comment by sadko4u** [comment]
Is there any way to make `clap-validator` skip this test?
The problem is, that this test stops me from integrating `clap-validator` into CI because it will always crash the validation process on `param-conversions` test.

I think it is an issue with clap validator because we do not need to rely on that the value is exactly the same way serialized to string and parsed back. This is the same as you try to compare two floats with `==` operator.

**Comment by robbert-vdh** [comment]
There's currently no way to whitelist specific parameters. But you can exclude the entire test with the `--test-filter` and `--invert-filter` options.

> I think it is an issue with clap validator because we do not need to rely on that the value is exactly the same way serialized to string and parsed back. This is the same as you try to compare two floats with == operator.

That's intentionally not how the test works. It generates a random value as a starting point, but setting a parameter to that value is expected to be lossy. So it instead converts that value to a string, and then starts checking the consistency of the conversions from there. If converting a string representation given by the plugin to a value and then back to a string yields a different string from the one given by the plugin before, then the plugin's output is nondeterministic. If you don't consider that to be a problem, you can indeed just exclude these test cases.
