### ISSUE TITLE
Any stable link for binaries?

### ISSUE THREAD

**Issue by sadko4u** [free-audio/clap-validator#8]
Hello!

I'm thinking on integrating `clap-validator` as a part of CI to my project - [LSP Plugins](https://github.com/sadko4u/lsp-plugins/).
Here's the [example of current CI pipeline](https://github.com/lsp-plugins/lsp-plugins-mb-compressor/actions/runs/3831341987).
It is OK to build the latest `clap-validator` from source but requires some time.
It would be nice to have a stable link to download the archive with binaries just to unpack them and run inside of the CI.

**Comment by robbert-vdh** [comment]
The links on https://nightly.link/free-audio/clap-validator/workflows/build/master are not stable as they contain version information.. Removing that would make them stable, but I'd like to avoid that. I also don't think there's a way to enumerate and download another repo's artifacts using GitHub Actions, is there? Do you have any suggestions?

**Comment by sadko4u** [comment]
We can just download archive with `wget` and unpack it.
There can be `clap-validator-latest` available for download near to the build with the lastest version, I think.

**Comment by robbert-vdh** [comment]
What I'm saying is that there is no `clap-validator-latest`. There is only a `clap-validator-0.1.0-5-g7995793-ubuntu-18.04`. I'd rather not drop the version information from the artifact name. But you can get a stable link to that artifact using:

https://nightly.link/free-audio/clap-validator/suites/10164113586/artifacts/496867785

So just take the artifact link from the GitHub Actions page and replace `github.com` in the URL with `nightly.link`. If you really want the latest version (which could cause your CI to fail at any point if new tests are added that do not pass for your plugin) then I guess you could also get this information using the GitHub API. You'll need to set the `GH_TOKEN` environment variable to avoid being rate limited as described here: https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api?apiVersion=2022-11-28#authentication-example-for-github-actions Then you can get the run ID of the last successful run like so: 

```bash
run_id=$(gh api '/repos/free-audio/clap-validator/actions/runs?branch=master&status=completed' --jq 'first(.workflow_runs[] | select(.name == "Automated Builds")).id')
```

You can then get the artifact ID with:

```bash
artifact_id=$(gh api "/repos/free-audio/clap-validator/actions/runs/$run_id/artifacts" --jq 'first(.artifacts[] | select(.name | contains("ubuntu"))).id')
```

And you can then download it like this:

```bash
gh api "/repos/free-audio/clap-validator/actions/artifacts/$artifact_id/zip" > artifact.zip && unzip artifact.zip && rm artifact.zip
```

Keep in mind that this will yield a `.tar.gz` file on Linux and macOS that then must also be extracted.

**Comment by robbert-vdh** [comment]
I've uploaded binaries to the [releases page](https://github.com/free-audio/clap-validator/releases). Those links will remain stable.
